//
//  TypeSwift
//  Created by Justin Bush (@buzsh)
//  https://typeswift.org
//  https://github.com/TypeSwift/TypeSwift
//
//  Generated by SwiftGen
//  DO NOT MODIFY THE CONTENTS OF THIS FILE
//

import SwiftUI

// TODO: ObservableWebView option
// TODO: TypeSafe modifiers for non-ObservableWebView code

struct TypeSafeScriptMessageHandlerModifier: ViewModifier {
  let handlerType: TypeSwift.MessageHandlers
  var manager: ObservableWebViewManager
  
  func body(content: Content) -> some View {
    content
      .onAppear {
        manager.removeScriptMessageHandler(forName: handlerType.name)
        manager.addScriptMessageHandler(ObservableScriptMessageHandler(handler: { message in
          handlerType.handle(message: message)
        }), forName: handlerType.name)
      }
  }
}

extension View {
  func tsMessageHandler(_ handlerType: TypeSwift.MessageHandlers, manager: ObservableWebViewManager) -> some View {
    self.modifier(TypeSafeScriptMessageHandlerModifier(handlerType: handlerType, manager: manager))
  }
}
